services:
  api:
    build: .
    environment:
      APP_PRICE_SOURCE_BASEURL: https://www.wafabourse.com
      APP_PORTFOLIOS_DIR: /data/portfolios
    ports:
      - "8080:8080"
    volumes:
      - portfolios:/data/portfolios

volumes:
  portfolios:
